//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class INTEGRADOEntities : DbContext
    {
        public INTEGRADOEntities()
            : base("name=INTEGRADOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TB_AL_Almacenes> TB_AL_Almacenes { get; set; }
        public DbSet<TB_AL_DetalleSolicitudEntrada> TB_AL_DetalleSolicitudEntrada { get; set; }
        public DbSet<TB_AL_DocumentosReferencia> TB_AL_DocumentosReferencia { get; set; }
        public DbSet<TB_AL_DocumentosReferenciaAjusteInventario> TB_AL_DocumentosReferenciaAjusteInventario { get; set; }
        public DbSet<TB_AL_DocumentosReferenciaGuiaEntrada> TB_AL_DocumentosReferenciaGuiaEntrada { get; set; }
        public DbSet<TB_AL_DocumentosReferenciaGuiaSalida> TB_AL_DocumentosReferenciaGuiaSalida { get; set; }
        public DbSet<TB_AL_Kardex> TB_AL_Kardex { get; set; }
        public DbSet<TB_AL_Productos> TB_AL_Productos { get; set; }
        public DbSet<TB_AL_ReservaStock> TB_AL_ReservaStock { get; set; }
        public DbSet<TB_AL_SolicitudesEntrada> TB_AL_SolicitudesEntrada { get; set; }
        public DbSet<TB_CA_DetalleOrdenCalidad> TB_CA_DetalleOrdenCalidad { get; set; }
        public DbSet<TB_CA_DetallePlanCalidad> TB_CA_DetallePlanCalidad { get; set; }
        public DbSet<TB_CA_Especialista> TB_CA_Especialista { get; set; }
        public DbSet<TB_CA_EspecialistaCalendario> TB_CA_EspecialistaCalendario { get; set; }
        public DbSet<TB_CA_IngenieriaProducto> TB_CA_IngenieriaProducto { get; set; }
        public DbSet<TB_CA_OrdenCalidad> TB_CA_OrdenCalidad { get; set; }
        public DbSet<TB_CA_PlanCalidad> TB_CA_PlanCalidad { get; set; }
        public DbSet<TB_CA_TipoPrueba> TB_CA_TipoPrueba { get; set; }
        public DbSet<TB_Contrato> TB_Contrato { get; set; }
        public DbSet<TB_CronogramaDespacho> TB_CronogramaDespacho { get; set; }
        public DbSet<TB_CronogramaEmbarque> TB_CronogramaEmbarque { get; set; }
        public DbSet<TB_DetalleRequerimiento> TB_DetalleRequerimiento { get; set; }
        public DbSet<TB_EX_DetalleDocExportacion> TB_EX_DetalleDocExportacion { get; set; }
        public DbSet<TB_EX_DocumentoExportacion> TB_EX_DocumentoExportacion { get; set; }
        public DbSet<TB_EX_DocumentoSIICEX> TB_EX_DocumentoSIICEX { get; set; }
        public DbSet<TB_EX_FormatoDocumento> TB_EX_FormatoDocumento { get; set; }
        public DbSet<TB_EX_IATA> TB_EX_IATA { get; set; }
        public DbSet<TB_EX_PackingList> TB_EX_PackingList { get; set; }
        public DbSet<TB_EX_SolicitudAtencion> TB_EX_SolicitudAtencion { get; set; }
        public DbSet<TB_Lotes> TB_Lotes { get; set; }
        public DbSet<TB_MA_Pais> TB_MA_Pais { get; set; }
        public DbSet<TB_ModalidadCredito> TB_ModalidadCredito { get; set; }
        public DbSet<TB_PR_LoteFabricacion> TB_PR_LoteFabricacion { get; set; }
        public DbSet<TB_PR_OrdenTrabajo> TB_PR_OrdenTrabajo { get; set; }
        public DbSet<TB_PV_Encuestas> TB_PV_Encuestas { get; set; }
        public DbSet<TB_PV_InformesReclamo> TB_PV_InformesReclamo { get; set; }
        public DbSet<TB_PV_InformesResultado> TB_PV_InformesResultado { get; set; }
        public DbSet<TB_PV_Plantillas> TB_PV_Plantillas { get; set; }
        public DbSet<TB_PV_PlantillasDetalle> TB_PV_PlantillasDetalle { get; set; }
        public DbSet<TB_PV_Programaciones> TB_PV_Programaciones { get; set; }
        public DbSet<TB_PV_Reclamos> TB_PV_Reclamos { get; set; }
        public DbSet<TB_PV_TiposPlantilla> TB_PV_TiposPlantilla { get; set; }
        public DbSet<TB_Requerimiento> TB_Requerimiento { get; set; }
        public DbSet<TB_RH_Empleados> TB_RH_Empleados { get; set; }
        public DbSet<TB_SE_Membership> TB_SE_Membership { get; set; }
        public DbSet<TB_SE_OAuthMembership> TB_SE_OAuthMembership { get; set; }
        public DbSet<TB_SE_Roles> TB_SE_Roles { get; set; }
        public DbSet<TB_SE_UserProfile> TB_SE_UserProfile { get; set; }
        public DbSet<TB_TipoLotes> TB_TipoLotes { get; set; }
        public DbSet<TB_VT_Categoria> TB_VT_Categoria { get; set; }
        public DbSet<TB_VT_Clientes> TB_VT_Clientes { get; set; }
        public DbSet<TB_VT_Contacto> TB_VT_Contacto { get; set; }
        public DbSet<TB_VT_DetallePedido> TB_VT_DetallePedido { get; set; }
        public DbSet<TB_VT_Direccion> TB_VT_Direccion { get; set; }
        public DbSet<TB_VT_FacturaDetalles> TB_VT_FacturaDetalles { get; set; }
        public DbSet<TB_VT_Facturas> TB_VT_Facturas { get; set; }
        public DbSet<TB_VT_GrupoVenta> TB_VT_GrupoVenta { get; set; }
        public DbSet<TB_VT_ListaPrecios> TB_VT_ListaPrecios { get; set; }
        public DbSet<TB_VT_Pedido> TB_VT_Pedido { get; set; }
        public DbSet<TB_VT_Telefono> TB_VT_Telefono { get; set; }
    }
}
