//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_AL_Productos
    {
        public TB_AL_Productos()
        {
            this.TB_AL_DetalleSolicitudEntrada = new HashSet<TB_AL_DetalleSolicitudEntrada>();
            this.TB_AL_Kardex = new HashSet<TB_AL_Kardex>();
            this.TB_VT_DetallePedido = new HashSet<TB_VT_DetallePedido>();
            this.TB_DetalleRequerimiento = new HashSet<TB_DetalleRequerimiento>();
            this.TB_VT_FacturaDetalles = new HashSet<TB_VT_FacturaDetalles>();
        }
    
        public int ProductoId { get; set; }
        public string CodigoProducto { get; set; }
        public string Nombre { get; set; }
        public string DescripcionCorta { get; set; }
        public string DescripcionLarga { get; set; }
        public string Unidad { get; set; }
        public double PrecioListaCompra { get; set; }
        public double PrecioListaVenta { get; set; }
        public int Estado { get; set; }
    
        public virtual ICollection<TB_AL_DetalleSolicitudEntrada> TB_AL_DetalleSolicitudEntrada { get; set; }
        public virtual ICollection<TB_AL_Kardex> TB_AL_Kardex { get; set; }
        public virtual ICollection<TB_VT_DetallePedido> TB_VT_DetallePedido { get; set; }
        public virtual ICollection<TB_DetalleRequerimiento> TB_DetalleRequerimiento { get; set; }
        public virtual ICollection<TB_VT_FacturaDetalles> TB_VT_FacturaDetalles { get; set; }
    }
}
