//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_AL_DocumentosReferencia
    {
        public TB_AL_DocumentosReferencia()
        {
            this.TB_AL_Kardex = new HashSet<TB_AL_Kardex>();
        }
    
        public int DocumentoReferenciaId { get; set; }
        public string IdentificadorDocumento { get; set; }
        public System.DateTime FechaElaboracion { get; set; }
        public string Observaciones { get; set; }
        public int AlmacenId { get; set; }
        public int EmpleadoId { get; set; }
    
        public virtual TB_AL_Almacenes TB_AL_Almacenes { get; set; }
        public virtual TB_AL_DocumentosReferenciaAjusteInventario TB_AL_DocumentosReferenciaAjusteInventario { get; set; }
        public virtual ICollection<TB_AL_Kardex> TB_AL_Kardex { get; set; }
        public virtual TB_RH_Empleados TB_RH_Empleados { get; set; }
    }
}
