//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_AL_Kardex
    {
        public int KardexId { get; set; }
        public int TipoMovimiento { get; set; }
        public string Cantidad { get; set; }
        public double ValorUnitario { get; set; }
        public int DocumentoReferenciaId { get; set; }
        public int AlmacenId { get; set; }
        public int ProductoId { get; set; }
    
        public virtual TB_AL_Almacenes TB_AL_Almacenes { get; set; }
        public virtual TB_AL_DocumentosReferencia TB_AL_DocumentosReferencia { get; set; }
        public virtual TB_AL_Productos TB_AL_Productos { get; set; }
    }
}
