//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_AL_SolicitudesEntrada
    {
        public TB_AL_SolicitudesEntrada()
        {
            this.TB_AL_DetalleSolicitudEntrada = new HashSet<TB_AL_DetalleSolicitudEntrada>();
            this.TB_AL_DocumentosReferenciaGuiaEntrada = new HashSet<TB_AL_DocumentosReferenciaGuiaEntrada>();
        }
    
        public int SolicitudEntradaId { get; set; }
        public System.DateTime FechaElaboracion { get; set; }
        public int TipoEntrada { get; set; }
        public int Estado { get; set; }
        public int EmpleadoId { get; set; }
    
        public virtual ICollection<TB_AL_DetalleSolicitudEntrada> TB_AL_DetalleSolicitudEntrada { get; set; }
        public virtual ICollection<TB_AL_DocumentosReferenciaGuiaEntrada> TB_AL_DocumentosReferenciaGuiaEntrada { get; set; }
        public virtual TB_RH_Empleados TB_RH_Empleados { get; set; }
    }
}
