//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CronogramaDespacho
    {
        public int Codigo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaDespacho { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<int> CodigoSolAtencion { get; set; }
    
        public virtual TB_EX_SolicitudAtencion TB_EX_SolicitudAtencion { get; set; }
    }
}
