//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CA_Especialista
    {
        public int IdEspecialista { get; set; }
        public string NombreEspecialista { get; set; }
        public string ApellidosEspecialista { get; set; }
        public string CodigoEspecialista { get; set; }
        public string Especialidad { get; set; }
    }
}
