//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CA_IngenieriaProducto
    {
        public int IDIngenieriaProducto { get; set; }
        public string codigoIngenieriaProducto { get; set; }
        public Nullable<double> valorPermitido { get; set; }
        public string UnidadMedida { get; set; }
        public Nullable<decimal> PoMuestra { get; set; }
        public Nullable<int> Codigo_Producto { get; set; }
        public Nullable<int> IdTipoPrueba { get; set; }
    }
}
