//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CA_EspecialistaCalendario
    {
        public int IdEspecialistaCalendario { get; set; }
        public Nullable<System.DateTime> FchInicio { get; set; }
        public Nullable<System.DateTime> FchFin { get; set; }
        public string EstadoEspecialistaCalendario { get; set; }
        public Nullable<int> IDEspecialista { get; set; }
    }
}
