//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DetalleRequerimiento
    {
        public Nullable<int> CodigoReq { get; set; }
        public int Cantidad { get; set; }
        public Nullable<decimal> CIF { get; set; }
        public Nullable<decimal> FOB { get; set; }
        public Nullable<int> CodigoDocExport { get; set; }
        public Nullable<int> CodigoSolAtencion { get; set; }
        public Nullable<int> ProductoId { get; set; }
        public Nullable<int> CodigoDocSiicex { get; set; }
    
        public virtual TB_AL_Productos TB_AL_Productos { get; set; }
        public virtual TB_EX_DocumentoExportacion TB_EX_DocumentoExportacion { get; set; }
        public virtual TB_EX_DocumentoSIICEX TB_EX_DocumentoSIICEX { get; set; }
        public virtual TB_Requerimiento TB_Requerimiento { get; set; }
        public virtual TB_EX_SolicitudAtencion TB_EX_SolicitudAtencion { get; set; }
    }
}
