//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EX_PackingList
    {
        public TB_EX_PackingList()
        {
            this.TB_EX_FormatoDocumento = new HashSet<TB_EX_FormatoDocumento>();
        }
    
        public int CodigoPickingList { get; set; }
        public Nullable<int> NroBulto { get; set; }
        public string Contenido { get; set; }
        public Nullable<int> Dimensiones { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<decimal> VolumenTotal { get; set; }
        public Nullable<decimal> PesoTotal { get; set; }
        public Nullable<decimal> PesoBrutoTotal { get; set; }
        public Nullable<int> CodigoSolAtencion { get; set; }
    
        public virtual ICollection<TB_EX_FormatoDocumento> TB_EX_FormatoDocumento { get; set; }
        public virtual TB_EX_SolicitudAtencion TB_EX_SolicitudAtencion { get; set; }
    }
}
