//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EX_DetalleDocExportacion
    {
        public int CodigoDocExport { get; set; }
        public Nullable<System.DateTime> FechaPublicacion { get; set; }
        public Nullable<System.DateTime> FechaExpiracion { get; set; }
        public string Version { get; set; }
        public string Estado { get; set; }
        public Nullable<double> DocumentoAdjunto { get; set; }
        public int CodigoDocSiicex { get; set; }
    
        public virtual TB_EX_DocumentoExportacion TB_EX_DocumentoExportacion { get; set; }
        public virtual TB_EX_DocumentoSIICEX TB_EX_DocumentoSIICEX { get; set; }
    }
}
