//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EX_DocumentoExportacion
    {
        public TB_EX_DocumentoExportacion()
        {
            this.TB_DetalleRequerimiento = new HashSet<TB_DetalleRequerimiento>();
            this.TB_EX_DetalleDocExportacion = new HashSet<TB_EX_DetalleDocExportacion>();
        }
    
        public int CodigoDocExport { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        public virtual ICollection<TB_DetalleRequerimiento> TB_DetalleRequerimiento { get; set; }
        public virtual ICollection<TB_EX_DetalleDocExportacion> TB_EX_DetalleDocExportacion { get; set; }
    }
}
