//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EX_SolicitudAtencion
    {
        public TB_EX_SolicitudAtencion()
        {
            this.TB_Contrato = new HashSet<TB_Contrato>();
            this.TB_CronogramaDespacho = new HashSet<TB_CronogramaDespacho>();
            this.TB_CronogramaEmbarque = new HashSet<TB_CronogramaEmbarque>();
            this.TB_DetalleRequerimiento = new HashSet<TB_DetalleRequerimiento>();
            this.TB_EX_PackingList = new HashSet<TB_EX_PackingList>();
            this.TB_VT_Facturas = new HashSet<TB_VT_Facturas>();
        }
    
        public int CodigoSolAtencion { get; set; }
        public string Responsable { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public System.DateTime FechaReservaEspacio { get; set; }
        public System.DateTime FechaDespacho { get; set; }
        public string Estado { get; set; }
        public string Observaciones { get; set; }
    
        public virtual TB_AL_ReservaStock TB_AL_ReservaStock { get; set; }
        public virtual ICollection<TB_Contrato> TB_Contrato { get; set; }
        public virtual ICollection<TB_CronogramaDespacho> TB_CronogramaDespacho { get; set; }
        public virtual ICollection<TB_CronogramaEmbarque> TB_CronogramaEmbarque { get; set; }
        public virtual ICollection<TB_DetalleRequerimiento> TB_DetalleRequerimiento { get; set; }
        public virtual ICollection<TB_EX_PackingList> TB_EX_PackingList { get; set; }
        public virtual ICollection<TB_VT_Facturas> TB_VT_Facturas { get; set; }
    }
}
