//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Lotes
    {
        public int LoteId { get; set; }
        public string NroLote { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int TipoLoteId { get; set; }
    
        public virtual TB_TipoLotes TB_TipoLotes { get; set; }
    }
}
