//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ModalidadCredito
    {
        public TB_ModalidadCredito()
        {
            this.TB_VT_Facturas = new HashSet<TB_VT_Facturas>();
        }
    
        public int ModalidadCreditoId { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public int DiasCredito { get; set; }
    
        public virtual ICollection<TB_VT_Facturas> TB_VT_Facturas { get; set; }
    }
}
