//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PV_Programaciones
    {
        public TB_PV_Programaciones()
        {
            this.TB_PV_Encuestas = new HashSet<TB_PV_Encuestas>();
        }
    
        public int ProgramacionId { get; set; }
        public string CodigoProgramacion { get; set; }
        public string Periodicidad { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public double PorcentajeEncuestados { get; set; }
        public string Descripcion { get; set; }
        public string Estado { get; set; }
        public short DiasVigencia { get; set; }
        public int PlantillaId { get; set; }
    
        public virtual ICollection<TB_PV_Encuestas> TB_PV_Encuestas { get; set; }
        public virtual TB_PV_Plantillas TB_PV_Plantillas { get; set; }
    }
}
