//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PV_InformesResultado
    {
        public int InformeResultadoId { get; set; }
        public string Descripcion { get; set; }
        public string FechaElaboracion { get; set; }
        public string FechaTabIni { get; set; }
        public string FechaTabFin { get; set; }
        public string DetalleAnalisis { get; set; }
        public int ElaboradoPorId { get; set; }
        public int PlantillaId { get; set; }
    
        public virtual TB_RH_Empleados TB_RH_Empleados { get; set; }
        public virtual TB_PV_Plantillas TB_PV_Plantillas { get; set; }
    }
}
