//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PR_OrdenTrabajo
    {
        public int OrdenId { get; set; }
        public Nullable<int> LoteId { get; set; }
        public string AreaTrabajo { get; set; }
        public Nullable<System.DateTime> FecIniciOrden { get; set; }
        public Nullable<System.DateTime> FecFinalOrden { get; set; }
        public string RecursoId { get; set; }
        public string DescRecurso { get; set; }
        public Nullable<int> CantRecursoDisp { get; set; }
        public string GlosaOrd { get; set; }
        public Nullable<int> EstOrden { get; set; }
    }
}
