//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PV_Encuestas
    {
        public TB_PV_Encuestas()
        {
            this.TB_PV_PlantillasDetalle = new HashSet<TB_PV_PlantillasDetalle>();
        }
    
        public int EncuestaId { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaRespuesta { get; set; }
        public string Titulo { get; set; }
        public int ClienteId { get; set; }
        public int ProgramacionId { get; set; }
    
        public virtual TB_PV_Programaciones TB_PV_Programaciones { get; set; }
        public virtual TB_VT_Clientes TB_VT_Clientes { get; set; }
        public virtual ICollection<TB_PV_PlantillasDetalle> TB_PV_PlantillasDetalle { get; set; }
    }
}
