//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Requerimiento
    {
        public TB_Requerimiento()
        {
            this.TB_DetalleRequerimiento = new HashSet<TB_DetalleRequerimiento>();
            this.TB_VT_Facturas = new HashSet<TB_VT_Facturas>();
        }
    
        public int CodigoReq { get; set; }
        public string Destino { get; set; }
        public string IATA { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaEsperada { get; set; }
        public decimal PrecioAprox { get; set; }
        public string Estado { get; set; }
        public string Observaciones { get; set; }
        public int ClienteId { get; set; }
        public Nullable<int> CodigoPais { get; set; }
    
        public virtual ICollection<TB_DetalleRequerimiento> TB_DetalleRequerimiento { get; set; }
        public virtual TB_MA_Pais TB_MA_Pais { get; set; }
        public virtual ICollection<TB_VT_Facturas> TB_VT_Facturas { get; set; }
        public virtual TB_VT_Clientes TB_VT_Clientes { get; set; }
    }
}
