//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_VT_Direccion
    {
        public TB_VT_Direccion()
        {
            this.TB_VT_Clientes = new HashSet<TB_VT_Clientes>();
        }
    
        public int DireccionId { get; set; }
        public int ClienteId { get; set; }
        public string Descripcion { get; set; }
        public bool DireccionPrincipal { get; set; }
    
        public virtual ICollection<TB_VT_Clientes> TB_VT_Clientes { get; set; }
    }
}
