//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_VT_Clientes
    {
        public TB_VT_Clientes()
        {
            this.TB_PV_Encuestas = new HashSet<TB_PV_Encuestas>();
            this.TB_Requerimiento = new HashSet<TB_Requerimiento>();
            this.TB_VT_Facturas = new HashSet<TB_VT_Facturas>();
            this.TB_VT_Pedido = new HashSet<TB_VT_Pedido>();
        }
    
        public int ClienteId { get; set; }
        public int TipoTerceroId { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string RazonSocial { get; set; }
        public int TipoDocIdentidadId { get; set; }
        public Nullable<int> Ruc { get; set; }
        public string DocIdentidad { get; set; }
        public bool Activo { get; set; }
        public int DireccionPrincipalId { get; set; }
        public string Direccion { get; set; }
        public decimal LineaCredito { get; set; }
        public int ModalidadCreditoId { get; set; }
        public int DiasCredito { get; set; }
        public int TipoMedioDePagoId { get; set; }
        public bool CreditoContado { get; set; }
        public int CategoriaClienteId { get; set; }
        public bool LineaCreditoActiva { get; set; }
        public string Email { get; set; }
        public string Codigo { get; set; }
        public string CodigoPais { get; set; }
        public int Telefono { get; set; }
        public string Observaciones { get; set; }
        public string Usuario { get; set; }
    
        public virtual ICollection<TB_PV_Encuestas> TB_PV_Encuestas { get; set; }
        public virtual ICollection<TB_Requerimiento> TB_Requerimiento { get; set; }
        public virtual TB_VT_Direccion TB_VT_Direccion { get; set; }
        public virtual ICollection<TB_VT_Facturas> TB_VT_Facturas { get; set; }
        public virtual ICollection<TB_VT_Pedido> TB_VT_Pedido { get; set; }
    }
}
