//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_VT_Pedido
    {
        public TB_VT_Pedido()
        {
            this.TB_VT_DetallePedido = new HashSet<TB_VT_DetallePedido>();
        }
    
        public int PedidoId { get; set; }
        public int ClienteId { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public System.DateTime FechaEntrega { get; set; }
        public int ModalidadCreditoId { get; set; }
        public System.DateTime FechaPago { get; set; }
        public bool Credito { get; set; }
        public string Direccion { get; set; }
        public int EmpleadoId { get; set; }
        public string Observacion { get; set; }
        public bool PrecioIncluyeImpuesto { get; set; }
        public string EstadoFacturacion { get; set; }
        public string DireccionEntrega { get; set; }
    
        public virtual TB_RH_Empleados TB_RH_Empleados { get; set; }
        public virtual TB_VT_Clientes TB_VT_Clientes { get; set; }
        public virtual ICollection<TB_VT_DetallePedido> TB_VT_DetallePedido { get; set; }
    }
}
