//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_VT_ListaPrecios
    {
        public int ListaPrecioId { get; set; }
        public string Codigo { get; set; }
        public string Descripción { get; set; }
        public string Sucursal { get; set; }
        public Nullable<bool> RestringuirZona { get; set; }
        public Nullable<bool> RestringuirGrupoVentas { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
