//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.MVC.PostVentaServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReclamoDto", Namespace="http://schemas.datacontract.org/2004/07/ETNA.DTOs.PV")]
    [System.SerializableAttribute()]
    public partial class ReclamoDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoReclamoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaHoraReclamoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFacturaDetalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreRegistradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroFacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoReclamo {
            get {
                return this.CodigoReclamoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoReclamoField, value) != true)) {
                    this.CodigoReclamoField = value;
                    this.RaisePropertyChanged("CodigoReclamo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionEstado {
            get {
                return this.DescripcionEstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionEstadoField, value) != true)) {
                    this.DescripcionEstadoField = value;
                    this.RaisePropertyChanged("DescripcionEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Detalle {
            get {
                return this.DetalleField;
            }
            set {
                if ((object.ReferenceEquals(this.DetalleField, value) != true)) {
                    this.DetalleField = value;
                    this.RaisePropertyChanged("Detalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaHoraReclamo {
            get {
                return this.FechaHoraReclamoField;
            }
            set {
                if ((this.FechaHoraReclamoField.Equals(value) != true)) {
                    this.FechaHoraReclamoField = value;
                    this.RaisePropertyChanged("FechaHoraReclamo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRespuesta {
            get {
                return this.FechaRespuestaField;
            }
            set {
                if ((this.FechaRespuestaField.Equals(value) != true)) {
                    this.FechaRespuestaField = value;
                    this.RaisePropertyChanged("FechaRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFacturaDetalle {
            get {
                return this.IdFacturaDetalleField;
            }
            set {
                if ((this.IdFacturaDetalleField.Equals(value) != true)) {
                    this.IdFacturaDetalleField = value;
                    this.RaisePropertyChanged("IdFacturaDetalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Motivo {
            get {
                return this.MotivoField;
            }
            set {
                if ((object.ReferenceEquals(this.MotivoField, value) != true)) {
                    this.MotivoField = value;
                    this.RaisePropertyChanged("Motivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCliente {
            get {
                return this.NombreClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreClienteField, value) != true)) {
                    this.NombreClienteField = value;
                    this.RaisePropertyChanged("NombreCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreProducto {
            get {
                return this.NombreProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreProductoField, value) != true)) {
                    this.NombreProductoField = value;
                    this.RaisePropertyChanged("NombreProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreRegistrador {
            get {
                return this.NombreRegistradorField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreRegistradorField, value) != true)) {
                    this.NombreRegistradorField = value;
                    this.RaisePropertyChanged("NombreRegistrador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroFactura {
            get {
                return this.NumeroFacturaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroFacturaField, value) != true)) {
                    this.NumeroFacturaField = value;
                    this.RaisePropertyChanged("NumeroFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observaciones {
            get {
                return this.ObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionesField, value) != true)) {
                    this.ObservacionesField = value;
                    this.RaisePropertyChanged("Observaciones");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PostVentaServices.IReclamos")]
    public interface IReclamos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclamos/InsertarReclamo", ReplyAction="http://tempuri.org/IReclamos/InsertarReclamoResponse")]
        int InsertarReclamo(string codigoReclamo, System.DateTime fechaHoraReclamo, string motivo, string detalle, string observaciones, System.DateTime fechaRespuesta, string estado, int idFacturaDetalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclamos/InsertarReclamo", ReplyAction="http://tempuri.org/IReclamos/InsertarReclamoResponse")]
        System.Threading.Tasks.Task<int> InsertarReclamoAsync(string codigoReclamo, System.DateTime fechaHoraReclamo, string motivo, string detalle, string observaciones, System.DateTime fechaRespuesta, string estado, int idFacturaDetalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclamos/EditarReclamo", ReplyAction="http://tempuri.org/IReclamos/EditarReclamoResponse")]
        bool EditarReclamo(int idReclamo, string codigoReclamo, System.DateTime fechaHoraReclamo, string motivo, string detalle, string observaciones, System.DateTime fechaRespuesta, string estado, int idFacturaDetalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclamos/EditarReclamo", ReplyAction="http://tempuri.org/IReclamos/EditarReclamoResponse")]
        System.Threading.Tasks.Task<bool> EditarReclamoAsync(int idReclamo, string codigoReclamo, System.DateTime fechaHoraReclamo, string motivo, string detalle, string observaciones, System.DateTime fechaRespuesta, string estado, int idFacturaDetalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclamos/ListaReclamos", ReplyAction="http://tempuri.org/IReclamos/ListaReclamosResponse")]
        ETNA.MVC.PostVentaServices.ReclamoDto[] ListaReclamos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclamos/ListaReclamos", ReplyAction="http://tempuri.org/IReclamos/ListaReclamosResponse")]
        System.Threading.Tasks.Task<ETNA.MVC.PostVentaServices.ReclamoDto[]> ListaReclamosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclamos/ObtenerReclamo", ReplyAction="http://tempuri.org/IReclamos/ObtenerReclamoResponse")]
        ETNA.MVC.PostVentaServices.ReclamoDto ObtenerReclamo(int idReclamo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclamos/ObtenerReclamo", ReplyAction="http://tempuri.org/IReclamos/ObtenerReclamoResponse")]
        System.Threading.Tasks.Task<ETNA.MVC.PostVentaServices.ReclamoDto> ObtenerReclamoAsync(int idReclamo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReclamosChannel : ETNA.MVC.PostVentaServices.IReclamos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReclamosClient : System.ServiceModel.ClientBase<ETNA.MVC.PostVentaServices.IReclamos>, ETNA.MVC.PostVentaServices.IReclamos {
        
        public ReclamosClient() {
        }
        
        public ReclamosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReclamosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReclamosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReclamosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int InsertarReclamo(string codigoReclamo, System.DateTime fechaHoraReclamo, string motivo, string detalle, string observaciones, System.DateTime fechaRespuesta, string estado, int idFacturaDetalle) {
            return base.Channel.InsertarReclamo(codigoReclamo, fechaHoraReclamo, motivo, detalle, observaciones, fechaRespuesta, estado, idFacturaDetalle);
        }
        
        public System.Threading.Tasks.Task<int> InsertarReclamoAsync(string codigoReclamo, System.DateTime fechaHoraReclamo, string motivo, string detalle, string observaciones, System.DateTime fechaRespuesta, string estado, int idFacturaDetalle) {
            return base.Channel.InsertarReclamoAsync(codigoReclamo, fechaHoraReclamo, motivo, detalle, observaciones, fechaRespuesta, estado, idFacturaDetalle);
        }
        
        public bool EditarReclamo(int idReclamo, string codigoReclamo, System.DateTime fechaHoraReclamo, string motivo, string detalle, string observaciones, System.DateTime fechaRespuesta, string estado, int idFacturaDetalle) {
            return base.Channel.EditarReclamo(idReclamo, codigoReclamo, fechaHoraReclamo, motivo, detalle, observaciones, fechaRespuesta, estado, idFacturaDetalle);
        }
        
        public System.Threading.Tasks.Task<bool> EditarReclamoAsync(int idReclamo, string codigoReclamo, System.DateTime fechaHoraReclamo, string motivo, string detalle, string observaciones, System.DateTime fechaRespuesta, string estado, int idFacturaDetalle) {
            return base.Channel.EditarReclamoAsync(idReclamo, codigoReclamo, fechaHoraReclamo, motivo, detalle, observaciones, fechaRespuesta, estado, idFacturaDetalle);
        }
        
        public ETNA.MVC.PostVentaServices.ReclamoDto[] ListaReclamos() {
            return base.Channel.ListaReclamos();
        }
        
        public System.Threading.Tasks.Task<ETNA.MVC.PostVentaServices.ReclamoDto[]> ListaReclamosAsync() {
            return base.Channel.ListaReclamosAsync();
        }
        
        public ETNA.MVC.PostVentaServices.ReclamoDto ObtenerReclamo(int idReclamo) {
            return base.Channel.ObtenerReclamo(idReclamo);
        }
        
        public System.Threading.Tasks.Task<ETNA.MVC.PostVentaServices.ReclamoDto> ObtenerReclamoAsync(int idReclamo) {
            return base.Channel.ObtenerReclamoAsync(idReclamo);
        }
    }
}
