//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.MVC.FacturasServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacturaDto", Namespace="http://schemas.datacontract.org/2004/07/ETNA.DTOs.PV")]
    [System.SerializableAttribute()]
    public partial class FacturaDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ETNA.MVC.FacturasServices.ClienteDto[] ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaFacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCompletoClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroFacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValorVentaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ETNA.MVC.FacturasServices.ClienteDto[] Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaFactura {
            get {
                return this.FechaFacturaField;
            }
            set {
                if ((this.FechaFacturaField.Equals(value) != true)) {
                    this.FechaFacturaField = value;
                    this.RaisePropertyChanged("FechaFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCompletoCliente {
            get {
                return this.NombreCompletoClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCompletoClienteField, value) != true)) {
                    this.NombreCompletoClienteField = value;
                    this.RaisePropertyChanged("NombreCompletoCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroFactura {
            get {
                return this.NroFacturaField;
            }
            set {
                if ((object.ReferenceEquals(this.NroFacturaField, value) != true)) {
                    this.NroFacturaField = value;
                    this.RaisePropertyChanged("NroFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PrecioVenta {
            get {
                return this.PrecioVentaField;
            }
            set {
                if ((this.PrecioVentaField.Equals(value) != true)) {
                    this.PrecioVentaField = value;
                    this.RaisePropertyChanged("PrecioVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ValorVenta {
            get {
                return this.ValorVentaField;
            }
            set {
                if ((this.ValorVentaField.Equals(value) != true)) {
                    this.ValorVentaField = value;
                    this.RaisePropertyChanged("ValorVenta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteDto", Namespace="http://schemas.datacontract.org/2004/07/ETNA.DTOs.PV")]
    [System.SerializableAttribute()]
    public partial class ClienteDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocIdentidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocIdentidad {
            get {
                return this.DocIdentidadField;
            }
            set {
                if ((object.ReferenceEquals(this.DocIdentidadField, value) != true)) {
                    this.DocIdentidadField = value;
                    this.RaisePropertyChanged("DocIdentidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacturaDetalleDto", Namespace="http://schemas.datacontract.org/2004/07/ETNA.DTOs.PV")]
    [System.SerializableAttribute()]
    public partial class FacturaDetalleDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstadoProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ETNA.MVC.FacturasServices.FacturaDto[] FacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaFacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroFacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioVentaProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ETNA.MVC.FacturasServices.ProductoDto[] ProductoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstadoProducto {
            get {
                return this.EstadoProductoField;
            }
            set {
                if ((this.EstadoProductoField.Equals(value) != true)) {
                    this.EstadoProductoField = value;
                    this.RaisePropertyChanged("EstadoProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ETNA.MVC.FacturasServices.FacturaDto[] Factura {
            get {
                return this.FacturaField;
            }
            set {
                if ((object.ReferenceEquals(this.FacturaField, value) != true)) {
                    this.FacturaField = value;
                    this.RaisePropertyChanged("Factura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaFactura {
            get {
                return this.FechaFacturaField;
            }
            set {
                if ((this.FechaFacturaField.Equals(value) != true)) {
                    this.FechaFacturaField = value;
                    this.RaisePropertyChanged("FechaFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProducto {
            get {
                return this.IdProductoField;
            }
            set {
                if ((this.IdProductoField.Equals(value) != true)) {
                    this.IdProductoField = value;
                    this.RaisePropertyChanged("IdProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCliente {
            get {
                return this.NombreClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreClienteField, value) != true)) {
                    this.NombreClienteField = value;
                    this.RaisePropertyChanged("NombreCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreProducto {
            get {
                return this.NombreProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreProductoField, value) != true)) {
                    this.NombreProductoField = value;
                    this.RaisePropertyChanged("NombreProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroFactura {
            get {
                return this.NroFacturaField;
            }
            set {
                if ((object.ReferenceEquals(this.NroFacturaField, value) != true)) {
                    this.NroFacturaField = value;
                    this.RaisePropertyChanged("NroFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PrecioVentaProducto {
            get {
                return this.PrecioVentaProductoField;
            }
            set {
                if ((this.PrecioVentaProductoField.Equals(value) != true)) {
                    this.PrecioVentaProductoField = value;
                    this.RaisePropertyChanged("PrecioVentaProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ETNA.MVC.FacturasServices.ProductoDto[] Producto {
            get {
                return this.ProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductoField, value) != true)) {
                    this.ProductoField = value;
                    this.RaisePropertyChanged("Producto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductoDto", Namespace="http://schemas.datacontract.org/2004/07/ETNA.DTOs")]
    [System.SerializableAttribute()]
    public partial class ProductoDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionCortaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionLargaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioListaCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioListaVentaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionCorta {
            get {
                return this.DescripcionCortaField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionCortaField, value) != true)) {
                    this.DescripcionCortaField = value;
                    this.RaisePropertyChanged("DescripcionCorta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionLarga {
            get {
                return this.DescripcionLargaField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionLargaField, value) != true)) {
                    this.DescripcionLargaField = value;
                    this.RaisePropertyChanged("DescripcionLarga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PrecioListaCompra {
            get {
                return this.PrecioListaCompraField;
            }
            set {
                if ((this.PrecioListaCompraField.Equals(value) != true)) {
                    this.PrecioListaCompraField = value;
                    this.RaisePropertyChanged("PrecioListaCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PrecioListaVenta {
            get {
                return this.PrecioListaVentaField;
            }
            set {
                if ((this.PrecioListaVentaField.Equals(value) != true)) {
                    this.PrecioListaVentaField = value;
                    this.RaisePropertyChanged("PrecioListaVenta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FacturasServices.IFacturas")]
    public interface IFacturas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacturas/ListaFacturas", ReplyAction="http://tempuri.org/IFacturas/ListaFacturasResponse")]
        ETNA.MVC.FacturasServices.FacturaDto[] ListaFacturas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacturas/ListaFacturas", ReplyAction="http://tempuri.org/IFacturas/ListaFacturasResponse")]
        System.Threading.Tasks.Task<ETNA.MVC.FacturasServices.FacturaDto[]> ListaFacturasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacturas/ObtenerFactura", ReplyAction="http://tempuri.org/IFacturas/ObtenerFacturaResponse")]
        ETNA.MVC.FacturasServices.FacturaDto ObtenerFactura(int idFactura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacturas/ObtenerFactura", ReplyAction="http://tempuri.org/IFacturas/ObtenerFacturaResponse")]
        System.Threading.Tasks.Task<ETNA.MVC.FacturasServices.FacturaDto> ObtenerFacturaAsync(int idFactura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacturas/ListaFacturaDetalles", ReplyAction="http://tempuri.org/IFacturas/ListaFacturaDetallesResponse")]
        ETNA.MVC.FacturasServices.FacturaDetalleDto[] ListaFacturaDetalles(int idFactura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacturas/ListaFacturaDetalles", ReplyAction="http://tempuri.org/IFacturas/ListaFacturaDetallesResponse")]
        System.Threading.Tasks.Task<ETNA.MVC.FacturasServices.FacturaDetalleDto[]> ListaFacturaDetallesAsync(int idFactura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacturas/NroPaginasPorDetalleNroFactura", ReplyAction="http://tempuri.org/IFacturas/NroPaginasPorDetalleNroFacturaResponse")]
        int[] NroPaginasPorDetalleNroFactura(string nroFactura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacturas/NroPaginasPorDetalleNroFactura", ReplyAction="http://tempuri.org/IFacturas/NroPaginasPorDetalleNroFacturaResponse")]
        System.Threading.Tasks.Task<int[]> NroPaginasPorDetalleNroFacturaAsync(string nroFactura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacturas/ListarDetallePorNroFactura", ReplyAction="http://tempuri.org/IFacturas/ListarDetallePorNroFacturaResponse")]
        ETNA.MVC.FacturasServices.FacturaDetalleDto[] ListarDetallePorNroFactura(string nroFactura, int nroPagina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacturas/ListarDetallePorNroFactura", ReplyAction="http://tempuri.org/IFacturas/ListarDetallePorNroFacturaResponse")]
        System.Threading.Tasks.Task<ETNA.MVC.FacturasServices.FacturaDetalleDto[]> ListarDetallePorNroFacturaAsync(string nroFactura, int nroPagina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacturas/ObtenerFacturaDetalle", ReplyAction="http://tempuri.org/IFacturas/ObtenerFacturaDetalleResponse")]
        ETNA.MVC.FacturasServices.FacturaDetalleDto ObtenerFacturaDetalle(int idDetalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacturas/ObtenerFacturaDetalle", ReplyAction="http://tempuri.org/IFacturas/ObtenerFacturaDetalleResponse")]
        System.Threading.Tasks.Task<ETNA.MVC.FacturasServices.FacturaDetalleDto> ObtenerFacturaDetalleAsync(int idDetalle);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFacturasChannel : ETNA.MVC.FacturasServices.IFacturas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FacturasClient : System.ServiceModel.ClientBase<ETNA.MVC.FacturasServices.IFacturas>, ETNA.MVC.FacturasServices.IFacturas {
        
        public FacturasClient() {
        }
        
        public FacturasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FacturasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FacturasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FacturasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ETNA.MVC.FacturasServices.FacturaDto[] ListaFacturas() {
            return base.Channel.ListaFacturas();
        }
        
        public System.Threading.Tasks.Task<ETNA.MVC.FacturasServices.FacturaDto[]> ListaFacturasAsync() {
            return base.Channel.ListaFacturasAsync();
        }
        
        public ETNA.MVC.FacturasServices.FacturaDto ObtenerFactura(int idFactura) {
            return base.Channel.ObtenerFactura(idFactura);
        }
        
        public System.Threading.Tasks.Task<ETNA.MVC.FacturasServices.FacturaDto> ObtenerFacturaAsync(int idFactura) {
            return base.Channel.ObtenerFacturaAsync(idFactura);
        }
        
        public ETNA.MVC.FacturasServices.FacturaDetalleDto[] ListaFacturaDetalles(int idFactura) {
            return base.Channel.ListaFacturaDetalles(idFactura);
        }
        
        public System.Threading.Tasks.Task<ETNA.MVC.FacturasServices.FacturaDetalleDto[]> ListaFacturaDetallesAsync(int idFactura) {
            return base.Channel.ListaFacturaDetallesAsync(idFactura);
        }
        
        public int[] NroPaginasPorDetalleNroFactura(string nroFactura) {
            return base.Channel.NroPaginasPorDetalleNroFactura(nroFactura);
        }
        
        public System.Threading.Tasks.Task<int[]> NroPaginasPorDetalleNroFacturaAsync(string nroFactura) {
            return base.Channel.NroPaginasPorDetalleNroFacturaAsync(nroFactura);
        }
        
        public ETNA.MVC.FacturasServices.FacturaDetalleDto[] ListarDetallePorNroFactura(string nroFactura, int nroPagina) {
            return base.Channel.ListarDetallePorNroFactura(nroFactura, nroPagina);
        }
        
        public System.Threading.Tasks.Task<ETNA.MVC.FacturasServices.FacturaDetalleDto[]> ListarDetallePorNroFacturaAsync(string nroFactura, int nroPagina) {
            return base.Channel.ListarDetallePorNroFacturaAsync(nroFactura, nroPagina);
        }
        
        public ETNA.MVC.FacturasServices.FacturaDetalleDto ObtenerFacturaDetalle(int idDetalle) {
            return base.Channel.ObtenerFacturaDetalle(idDetalle);
        }
        
        public System.Threading.Tasks.Task<ETNA.MVC.FacturasServices.FacturaDetalleDto> ObtenerFacturaDetalleAsync(int idDetalle) {
            return base.Channel.ObtenerFacturaDetalleAsync(idDetalle);
        }
    }
}
