//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlantillaDetalle
    {
        public PlantillaDetalle()
        {
            this.Encuesta = new HashSet<Encuesta>();
        }
    
        public int Id { get; set; }
        public string CodigoPregunta { get; set; }
        public string DescripcionPregunta { get; set; }
        public string Respuesta1 { get; set; }
        public string Respuesta2 { get; set; }
        public string Respuesta3 { get; set; }
        public string Respuesta4 { get; set; }
        public string Respuesta5 { get; set; }
    
        public virtual Plantilla Plantilla { get; set; }
        public virtual ICollection<Encuesta> Encuesta { get; set; }
    }
}
