//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programacion
    {
        public int Id { get; set; }
        public string CodigoProgramacion { get; set; }
        public string Periodicidad { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public double PorcentajeEncuestados { get; set; }
        public string Descripcion { get; set; }
        public string Estado { get; set; }
        public short DiasVigencia { get; set; }
    
        public virtual Plantilla Plantilla { get; set; }
    }
}
