//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reclamo
    {
        public int Id { get; set; }
        public string CodigoReclamo { get; set; }
        public System.DateTime FechaHoraReclamo { get; set; }
        public string Motivo { get; set; }
        public string Detalle { get; set; }
        public string Observaciones { get; set; }
        public System.DateTime FechaRespuesta { get; set; }
        public string Estado { get; set; }
    
        public virtual Empleado RegistradoPor { get; set; }
        public virtual FacturaDetalle FacturaDetalle { get; set; }
    }
}
